version: '3.4'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: redwoodjs
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - dev
    ports:
      - 5432:5432

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: postgres@example.com
      PGADMIN_DEFAULT_PASSWORD: password
    volumes:
      - pgadmin:/var/lib/postgresql/data
    networks:
      - dev
    ports:
      - 81:80

volumes:
  db:
  pgadmin:

networks:
  dev:
